---
apiVersion: v1
kind: Pod
metadata:
  name: breakout
  namespace: default
  labels:
    app: breakout
spec:
  containers:
    - image: rbac-breakout:latest
      # This assumes the image is built / present on the node already.
      imagePullPolicy: Never
      name: breakout
      ports:
        - containerPort: 80
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: breakout
  namespace: default
spec:
  type: NodePort
  selector:
    app: breakout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
