---
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:

  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Build container
        run: docker build -t rbac-breakout:latest .

      - name: Start Docker container
        run: docker run -d -p 80:80 rbac-breakout:latest

      - name: Make sure the page loads.
        run: curl localhost
