---
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * 0'

jobs:

  dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build container
        run: docker build -t rbac-breakout:latest .

      - name: Start Docker container
        run: docker run -d -p 80:80 rbac-breakout:latest

      - name: Make sure the page loads.
        run: curl --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 localhost
